// vue-todo/src/ToDo.vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <h1 class="header">Vue To Do</h1>
    <div class="container">
      <div>
        <input type="text" v-model="todo" v-on:keyup.enter="createNewToDoItem" />
        <div class="btn-add" @click="createNewToDoItem()">+</div>
      </div>
      <div class="content">
        <ToDoItem v-for="todo in list"
        :todo="todo"
        @delete="onDeleteItem"
        :key="todo.id" />
      </div>
    </div>
  </div>
</template>

<script>
import ToDoItem from './components/ToDoItem.vue'

export default {
  name: 'app',
  components: {
    ToDoItem
  },
  data() {
    return {
      list: [
        {
          id: 1,
          text: 'feed pets'
        },
        {
          id: 2,
          text: 'return library books'
        }
      ],
      todo: ''
    }
  },

  methods: {
    createNewToDoItem() {
      if(!this.todo) {
        alert("please enter a todo!");
        return;
      }

      const newId = Math.max.apply(null, this.list.map(t => t.id)) + 1;
      this.list.push({ id: newId, text: this.todo });
      this.todo = '';
    },

    onDeleteItem(todo) {
      this.list = this.list.filter(item => item !== todo);
    }
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// react-todo/src/ToDo.js
import React, { Component } from 'react';
import logo from './assets/logo.svg';
import './ToDo.css';
import ToDoItem from './components/ToDoItem';

class ToDo extends Component {
  constructor(props) {
    super(props);
    this.state = {
      list: [
        {
          'todo': 'feed pets'
        },
        {
          'todo': 'learn to read'
        }
      ],
      todo: ''
    };
  };

  createNewToDoItem = () => {
    this.setState(({list, todo}) => ({
      list: [
        ...list, { todo }
      ],
      todo: ''
    }));
  };

  deleteItem = indexToDelete => {
    this.setState(({list}) => ({
      list: list.filter((toDo, index) => index !== indexToDelete)
    }));
  };

  handleKeyPress = e => {
    if(e.target.value !== '') {
      if  (e.key === 'Enter') {
        this.createNewToDoItem();
      }
    }
  };

  handleInput = e => {
    //console.log(e.target.value)
    this.setState({
      todo: e.target.value
    })
  }

  render() {
    return (
      <div className="todoApp">
        <img src={logo} className="App-logo" alt="logo" />
        <h1 className="header">React To Do</h1>
        <div className="container">
          <div className="container-flex">
            <input className="input" type="text" value={this.state.todo} onChange={this.handleInput} onKeyPress={this.handleKeyPress} />
            <div className="btn-add" onClick={this.createNewToDoItem}>+</div>
          </div>
          <ul className="list">
            {this.state.list.map((item,key) => {
              return <ToDoItem key={key} item={item.todo} deleteItem={this.deleteItem.bind(this,key)}/>
            })}
          </ul>
        </div>
      </div>
    );
  }
}

export default ToDo;
